apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: worker
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/startup-cpu-boost: "true"
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "2"
    spec:
      containerConcurrency: 1
      timeoutSeconds: 300
      containers:
        - image: us-central1-docker.pkg.dev/autoroad-479522/worker/worker:latest
          resources:
            limits:
              cpu: "8"
              memory: 4Gi
